/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package masterData;

import config.koneksi;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.*;
import javax.swing.JLabel;
import masterData.ItemCombo;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
public class form_guru extends javax.swing.JPanel {

    public Statement stat;
    public ResultSet res;
    Connection cn = config.koneksi.BukaKoneksi(); //package.nama file.class untuk koneksinya
    
    public form_guru() {
        initComponents();
        
        JTableHeader header = tbldataGuru.getTableHeader();
    header.setDefaultRenderer(new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

        JLabel label = (JLabel) super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);
        
        label.setBackground(new Color(32, 136, 203)); // biru
        label.setForeground(Color.WHITE); // teks putih
        label.setFont(new Font("Segoe UI", Font.BOLD, 15));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setOpaque(true); // WAJIB supaya background tampil

        return label;
    }
});

    }
    

    
     private void bersih () {
          tx_Id.setText("");
        tx_namaGuru.setText("");
        tx_nip.setText("");
        btn_simpan.setText("SIMPAN");
        btn_tambah.setText("TAMBAH");
        tx_Id.setEditable(true);
        
    }
    private void CariData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Id");
    model.addColumn("Nama Guru");
    model.addColumn("Status");
    model.addColumn("Nip");

    String cari = tx_cari.getText(); // txtCari adalah JTextField buat input pencarian

    try {
        String sql = "SELECT * FROM data_guru WHERE " +
                     "Id LIKE ? OR " +
                     "Nama_Guru LIKE ? OR " +
                     "Status LIKE ? OR " +
                     "Nip LIKE ?";
        
        java.sql.Connection conn = (java.sql.Connection) koneksi.BukaKoneksi();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        for (int i = 1; i <= 4; i++) {
            pst.setString(i, "%" + cari + "%");
        }

        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("Id"),
                rs.getString("Nama_Guru"),
                rs.getString("Status"),
                rs.getString("Nip")
            });
        }

        tbldataGuru.setModel(model); // tabelBarang adalah JTable buat nampilin data

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}

     
public void TampilData() {
    try {
        String sql = "SELECT * FROM data_guru ORDER BY Id ASC"; 
        stat = cn.createStatement();
        res = stat.executeQuery(sql); // gunakan query yg udah disiapin

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Guru");
        model.addColumn("Status");
        model.addColumn("NIP/NIPPPK/NIPKTT");

        model.setRowCount(0); // cukup ini aja, udah bersihin tabel

        while (res.next()) {
            Object[] data = {
                res.getString("Id"),
                res.getString("Nama_Guru"),
                res.getString("Status"),
                res.getString("Nip")
            };
            model.addRow(data);
        }

        tbldataGuru.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}

     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        data_guru = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldataGuru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tx_cari = new javax.swing.JTextField();
        form_guru = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_batal2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tx_namaGuru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_nip = new javax.swing.JTextField();
        cb_status = new javax.swing.JComboBox<>();
        tx_Id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_guru.setBackground(new java.awt.Color(255, 255, 255));

        tbldataGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbldataGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Guru", "Status", "NIP/NIPPPK/NIPKTT"
            }
        ));
        tbldataGuru.setFocusable(false);
        tbldataGuru.setGridColor(new java.awt.Color(153, 153, 153));
        tbldataGuru.setRowHeight(25);
        tbldataGuru.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbldataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldataGuru);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Guru");

        btn_tambah.setBackground(new java.awt.Color(0, 153, 255));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 255));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari");

        tx_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_guruLayout = new javax.swing.GroupLayout(data_guru);
        data_guru.setLayout(data_guruLayout);
        data_guruLayout.setHorizontalGroup(
            data_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_guruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addGroup(data_guruLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(data_guruLayout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tx_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        data_guruLayout.setVerticalGroup(
            data_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(data_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tx_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        main_panel.add(data_guru, "card2");

        form_guru.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Data Guru");

        btn_simpan.setBackground(new java.awt.Color(0, 153, 255));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal2.setBackground(new java.awt.Color(255, 255, 255));
        btn_batal2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_batal2.setText("BATAL");
        btn_batal2.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nama Guru ");

        tx_namaGuru.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Status");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("NIP/NIPPPK/NIPKTT");

        tx_nip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cb_status.setBackground(new java.awt.Color(0, 153, 255));
        cb_status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_status.setForeground(new java.awt.Color(255, 255, 255));
        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNS", "PPPK", "PKT", " " }));

        tx_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Id ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_namaGuru)
            .addComponent(tx_nip)
            .addComponent(cb_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tx_Id)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout form_guruLayout = new javax.swing.GroupLayout(form_guru);
        form_guru.setLayout(form_guruLayout);
        form_guruLayout.setHorizontalGroup(
            form_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_guruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(form_guruLayout.createSequentialGroup()
                        .addGroup(form_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(form_guruLayout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        form_guruLayout.setVerticalGroup(
            form_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(form_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_panel.add(form_guru, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       if (tx_Id.getText().equals("")) {
    JOptionPane.showMessageDialog(this, "Silahkan klik data yang akan dihapus!");
} else {
    int jawab = JOptionPane.showConfirmDialog(null, "Anda yakin ingin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (jawab == JOptionPane.YES_OPTION) {
        try {
            stat = cn.createStatement();
            String sql = "DELETE FROM data_guru WHERE Id ='" + tx_Id.getText().trim() + "'";
            System.out.println("Query: " + sql); // Debug
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            TampilData();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus! Error: " + e.getMessage());
        }
    }
}   
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tbldataGuru.clearSelection();
        bersih();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal2ActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(data_guru);
        main_panel.repaint();
        main_panel.revalidate();
        tbldataGuru.clearSelection();
        bersih();
    }//GEN-LAST:event_btn_batal2ActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
              main_panel.removeAll();
              main_panel.repaint();
              main_panel.revalidate();
        
              main_panel.add(form_guru);
              main_panel.repaint();
              main_panel.revalidate();
        if (btn_tambah.getText().equals("UBAH")) {
              btn_simpan.setText("UBAH");
              main_panel.removeAll();
              main_panel.repaint();
              main_panel.revalidate();
        
              main_panel.add(form_guru);
              main_panel.repaint();
              main_panel.revalidate();   
         }

        
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
         try {
    stat = cn.createStatement();

    // Validasi input kosong
    if (tx_Id.getText().equals("") ||
        tx_namaGuru.getText().equals("") ||
        tx_nip.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    if (btn_simpan.getText().equals("SIMPAN")) {
        // Cek apakah ID sudah ada
        String cek = "SELECT * FROM data_guru WHERE id='" + tx_Id.getText() + "'";
        res = stat.executeQuery(cek);
        if (res.next()) {
            JOptionPane.showMessageDialog(null, "ID sudah ada!");
        } 
        else {
            // Insert data baru
            String sql = "INSERT INTO data_guru VALUES ('" + tx_Id.getText() +
             "','" + tx_namaGuru.getText() +
             "','" + cb_status.getSelectedItem().toString() +
             "','" + tx_nip.getText() + "')";

            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Berhasil input data!");
            bersih();
            main_panel.removeAll();
            main_panel.repaint();
            main_panel.revalidate();
        
            main_panel.add(data_guru);
            main_panel.repaint();
            main_panel.revalidate();
            TampilData();
        } 
        

    } else{
            String edit = "UPDATE data_guru SET Nama_Guru = '" + tx_namaGuru.getText() +
              "', Status = '" + cb_status.getSelectedItem().toString() +
              "', Nip = '" + tx_nip.getText() +
              "' WHERE Id = '" + tx_Id.getText() + "'";

        stat.executeUpdate(edit);
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
              main_panel.removeAll();
              main_panel.repaint();
              main_panel.revalidate();
        
              main_panel.add(data_guru);
              main_panel.repaint();
              main_panel.revalidate(); 
        TampilData();
                
        }
        bersih();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tbldataGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataGuruMouseClicked
        tx_Id.setText(tbldataGuru.getValueAt(tbldataGuru.getSelectedRow(),0).toString());
        tx_namaGuru.setText(tbldataGuru.getValueAt(tbldataGuru.getSelectedRow(),1).toString());
        cb_status.setSelectedItem(tbldataGuru.getValueAt(tbldataGuru.getSelectedRow(),2).toString());
        tx_nip.setText(tbldataGuru.getValueAt(tbldataGuru.getSelectedRow(),3).toString());
       
        tx_Id.setEditable(false);
        btn_tambah.setText("UBAH");

        

    }//GEN-LAST:event_tbldataGuruMouseClicked

    private void tx_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cariActionPerformed
            // TODO add your handling code here:
            CariData();
    }//GEN-LAST:event_tx_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal2;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JPanel data_guru;
    private javax.swing.JPanel form_guru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTable tbldataGuru;
    private javax.swing.JTextField tx_Id;
    private javax.swing.JTextField tx_cari;
    private javax.swing.JTextField tx_namaGuru;
    private javax.swing.JTextField tx_nip;
    // End of variables declaration//GEN-END:variables
}
