
package main4;

/**
 *
 * @author Galuh Prandika
 */

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JCalendar;



public class form_pinjaman extends javax.swing.JPanel {
   
    Statement stat;
    ResultSet res;
    Connection cn = config.koneksi.BukaKoneksi();
    DefaultTableModel tabModel;
    String sql;
    
    
    public form_pinjaman() {
        initComponents();
        bersih();
        TampilData();
    }
    
    private void bersih() {
    tx_Id.setText("");
    tx_namaGuru.setText("");
    tx_Jumlah.setText("");
    jComboJenis.setSelectedIndex(0);
    JCalendar1.setDate(new Date());
    JCalendar2.setDate(new Date());
    tx_Id.setEditable(true);
    btn_tambah5.setText("TAMBAH");
    tbldatapinjaman1.clearSelection();
    }
    
    public void TampilData() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Id", "Nama Guru", "Jenis Pinjaman",
                             "Jumlah Pinjaman", "Tanggal Pinjam", "Jatuh Tempo"}, 0);

            stat = cn.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM pinjaman_guru");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_guru"),
                    rs.getString("nama_guru"),
                    rs.getString("jenis_pinjaman"),
                    rs.getInt("jumlah_pinjaman"),
                    rs.getDate("tanggal_pinjam"),
                    rs.getDate("tanggal_jatuh_tempo")
                });
            }
            tbldatapinjaman1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menampilkan data: " + e.getMessage());
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        data_pinjaman1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbldatapinjaman1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btn_tambah5 = new javax.swing.JButton();
        btn_hapus5 = new javax.swing.JButton();
        btn_batal6 = new javax.swing.JButton();
        form_pinjaman = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_batal2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tx_namaGuru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_Jumlah = new javax.swing.JTextField();
        tx_Id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboJenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel8 = new javax.swing.JLabel();
        JCalendar2 = new com.toedter.calendar.JCalendar();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_pinjaman1.setBackground(new java.awt.Color(255, 255, 255));

        tbldatapinjaman1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbldatapinjaman1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Guru", "Jenis Pinjaman", "Jumlah Pinjaman", "Tanggal Pinjaman", "Jatuh Tempo"
            }
        ));
        tbldatapinjaman1.setGridColor(new java.awt.Color(153, 153, 153));
        tbldatapinjaman1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataPinjamanMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbldatapinjaman1);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Data Pinjaman");

        btn_tambah5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tambah5.setText("TAMBAH");
        btn_tambah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_hapus5.setText("HAPUS");
        btn_hapus5.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_hapus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_batal6.setText("BATAL");
        btn_batal6.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_batal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_pinjaman1Layout = new javax.swing.GroupLayout(data_pinjaman1);
        data_pinjaman1.setLayout(data_pinjaman1Layout);
        data_pinjaman1Layout.setHorizontalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .addGroup(data_pinjaman1Layout.createSequentialGroup()
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                                .addComponent(btn_tambah5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_hapus5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_batal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        data_pinjaman1Layout.setVerticalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(14, 14, 14)
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
        );

        main_panel.add(data_pinjaman1, "card2");

        form_pinjaman.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Data Simpanan");

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_batal2.setText("BATAL");
        btn_batal2.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nama Guru ");

        tx_namaGuru.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Pinjaman");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Jumlah Pinjaman");

        tx_Jumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tx_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Id ");

        jComboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Konsumtif", "Produktif", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tanggal Pinjam");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Jatuh Tempo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_namaGuru)
            .addComponent(tx_Jumlah)
            .addComponent(tx_Id)
            .addComponent(jComboJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(JCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(JCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 588, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(JCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(JCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout form_pinjamanLayout = new javax.swing.GroupLayout(form_pinjaman);
        form_pinjaman.setLayout(form_pinjamanLayout);
        form_pinjamanLayout.setHorizontalGroup(
            form_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_pinjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(form_pinjamanLayout.createSequentialGroup()
                        .addGroup(form_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(form_pinjamanLayout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        form_pinjamanLayout.setVerticalGroup(
            form_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_pinjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(form_pinjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.add(form_pinjaman, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    private void btn_batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal2ActionPerformed
    bersih();
    btn_simpan.setText("SIMPAN");
    }//GEN-LAST:event_btn_batal2ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    String id = tx_Id.getText();
    String namaGuru = tx_namaGuru.getText();
    String jenisPinjaman = jComboJenis.getSelectedItem().toString();
    String jumlah = tx_Jumlah.getText();

    // Ambil tanggal dari JCalendar
    java.sql.Date tglPinjam = new java.sql.Date(JCalendar1.getDate().getTime());
    java.sql.Date tglJatuhTempo = new java.sql.Date(JCalendar2.getDate().getTime());

    try {
        if (btn_tambah5.getText().equals("TAMBAH")) {
            // Insert data baru
            sql = "INSERT INTO pinjaman_guru (kode_guru, nama_guru, jenis_pinjaman, jumlah_pinjaman, tanggal_pinjam, tanggal_jatuh_tempo) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, namaGuru);
            pst.setString(3, jenisPinjaman);
            pst.setInt(4, Integer.parseInt(jumlah));
            pst.setDate(5, tglPinjam);
            pst.setDate(6, tglJatuhTempo);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        } else if (btn_tambah5.getText().equals("UBAH")) {
            // Update data yang sudah ada
            sql = "UPDATE pinjaman_guru SET nama_guru=?, jenis_pinjaman=?, jumlah_pinjaman=?, tanggal_pinjam=?, tanggal_jatuh_tempo=? WHERE kode_guru=?";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, namaGuru);
            pst.setString(2, jenisPinjaman);
            pst.setInt(3, Integer.parseInt(jumlah));
            pst.setDate(4, tglPinjam);
            pst.setDate(5, tglJatuhTempo);
            pst.setString(6, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");

            // Kembali ke mode tambah setelah update
            btn_tambah5.setText("TAMBAH");
            tx_Id.setEditable(true);
        }

        bersih();
        TampilData();

        // Tampilkan panel data kembali
        main_panel.removeAll();
        main_panel.add(data_pinjaman1);
        main_panel.repaint();
        main_panel.revalidate();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        main_panel.add(data_pinjaman1);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int row = tbldatapinjaman1.getSelectedRow();
        if (row >= 0) {
            String id = tbldatapinjaman1.getValueAt(row, 0).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    sql = "DELETE FROM pinjaman_guru WHERE kode_guru=?";
                    PreparedStatement pst = cn.prepareStatement(sql);
                    pst.setString(1, id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    TampilData();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
    int selectedRow = tbldatapinjaman1.getSelectedRow();

    if (btn_tambah5.getText().equals("UBAH")) {
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit.");
            return;
        }

        
        String id = tbldatapinjaman1.getValueAt(selectedRow, 0).toString();
        String nama = tbldatapinjaman1.getValueAt(selectedRow, 1).toString();
        String jenis = tbldatapinjaman1.getValueAt(selectedRow, 2).toString();
        String jumlah = tbldatapinjaman1.getValueAt(selectedRow, 3).toString();
        Date tanggalPinjam = (Date) tbldatapinjaman1.getValueAt(selectedRow, 4);
        Date jatuhTempo = (Date) tbldatapinjaman1.getValueAt(selectedRow, 5);

        
        tx_Id.setText(id);
        tx_Id.setEditable(false); 
        tx_namaGuru.setText(nama);
        jComboJenis.setSelectedItem(jenis);
        tx_Jumlah.setText(jumlah);
        JCalendar1.setDate(tanggalPinjam);
        JCalendar2.setDate(jatuhTempo);

        
        main_panel.removeAll();
        main_panel.add(form_pinjaman);
        main_panel.repaint();
        main_panel.revalidate();
    } else {
        
        bersih();
        main_panel.removeAll();
        main_panel.add(form_pinjaman);
        main_panel.repaint();
        main_panel.revalidate();
    }
    
    }//GEN-LAST:event_btn_tambahActionPerformed

    
    private void tbldataPinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataPinjamanMouseClicked
    int row = tbldatapinjaman1.getSelectedRow();
    if (row != -1) {
        // Ambil data dari tabel
        String id = tbldatapinjaman1.getValueAt(row, 0).toString();
        String nama = tbldatapinjaman1.getValueAt(row, 1).toString();
        String jenis = tbldatapinjaman1.getValueAt(row, 2).toString();
        String jumlah = tbldatapinjaman1.getValueAt(row, 3).toString();
        Date tglPinjam = (Date) tbldatapinjaman1.getValueAt(row, 4);
        Date tglJatuhTempo = (Date) tbldatapinjaman1.getValueAt(row, 5);

        // Isi ke form tapi jangan ganti panel dulu
        tx_Id.setText(id);
        tx_namaGuru.setText(nama);
        jComboJenis.setSelectedItem(jenis);
        tx_Jumlah.setText(jumlah);
        JCalendar1.setDate(tglPinjam);
        JCalendar2.setDate(tglJatuhTempo);

        tx_Id.setEditable(false);  // biasanya id tidak boleh diedit saat update
        btn_tambah5.setText("UBAH"); // ganti tombol tambah jadi ubah
    }
    }//GEN-LAST:event_tbldataPinjamanMouseClicked
    
    private void isiFormDariTabel() {
    int row = tbldatapinjaman1.getSelectedRow();
    if (row != -1) {
        tx_Id.setText(tbldatapinjaman1.getValueAt(row, 0).toString());
        tx_namaGuru.setText(tbldatapinjaman1.getValueAt(row, 1).toString());
        jComboJenis.setSelectedItem(tbldatapinjaman1.getValueAt(row, 2).toString());
        tx_Jumlah.setText(tbldatapinjaman1.getValueAt(row, 3).toString());
        
        try {
            java.util.Date tglPinjam = (java.util.Date) tbldatapinjaman1.getValueAt(row, 4);
            java.util.Date tglJatuhTempo = (java.util.Date) tbldatapinjaman1.getValueAt(row, 5);
            JCalendar1.setDate(tglPinjam);
            JCalendar2.setDate(tglJatuhTempo);
        } catch (Exception e) {
            e.printStackTrace();
        }

        tx_Id.setEditable(false); // saat ubah, ID tidak boleh diganti
        btn_tambah5.setText("UBAH");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu dari tabel.");
    }
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar JCalendar1;
    private com.toedter.calendar.JCalendar JCalendar2;
    private javax.swing.JButton btn_batal2;
    private javax.swing.JButton btn_batal6;
    private javax.swing.JButton btn_hapus5;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah5;
    private javax.swing.JPanel data_pinjaman1;
    private javax.swing.JPanel form_pinjaman;
    private javax.swing.JComboBox<String> jComboJenis;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTable tbldatapinjaman1;
    private javax.swing.JTextField tx_Id;
    private javax.swing.JTextField tx_Jumlah;
    private javax.swing.JTextField tx_namaGuru;
    // End of variables declaration//GEN-END:variables

    private void updateData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
