/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class home1 extends javax.swing.JPanel {

   
    public home1() {
        initComponents();
        JPanel1.add(Box.createVerticalGlue());

        JPanel1.setLayout(new BoxLayout(JPanel1, BoxLayout.Y_AXIS));
        jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT);
        JPanel1 = new javax.swing.JPanel();
        // Tambahkan di sini
        JPanel1.setLayout(new BoxLayout(JPanel1, BoxLayout.Y_AXIS));
        JPanel1.add(Box.createVerticalGlue());




    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));
        JPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/sekolah.png"))); // NOI18N
        JPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("jLabel2");
        JPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        add(JPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
