
package report;

/**
 *
 * @author Galuh Prandika
 */

import masterData.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;



public class report_pinjaman extends javax.swing.JPanel {
   
    Statement stat;
    ResultSet res;
    Connection cn = config.koneksi.BukaKoneksi();
    DefaultTableModel tabModel;
    String sql;
    
    
    public report_pinjaman() {
        initComponents();
        TampilData();
        
        JTableHeader header = tbldatapinjaman1.getTableHeader();
    header.setDefaultRenderer(new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

        JLabel label = (JLabel) super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);
        
        label.setBackground(new Color(32, 136, 203)); // biru
        label.setForeground(Color.WHITE); // teks putih
        label.setFont(new Font("Segoe UI", Font.BOLD, 15));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setOpaque(true); // WAJIB supaya background tampil

        return label;
    }
});
    }
    
    
    public void TampilData() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Id", "Nama Guru", "Jenis Pinjaman",
                             "Jumlah Pinjaman", "Tanggal Pinjam", "Jatuh Tempo"}, 0);

            stat = cn.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM pinjaman_guru");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("nama_guru"),
                    rs.getString("jenis_pinjaman"),
                    rs.getInt("jumlah_pinjaman"),
                    rs.getDate("tanggal_pinjam"),
                    rs.getDate("tanggal_jatuh_tempo")
                });
            }
            tbldatapinjaman1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menampilkan data: " + e.getMessage());
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        data_pinjaman1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbldatapinjaman1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btn_tambah5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_pinjaman1.setBackground(new java.awt.Color(255, 255, 255));

        tbldatapinjaman1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbldatapinjaman1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Guru", "Jenis Pinjaman", "Jumlah Pinjaman", "Tanggal Pinjaman", "Jatuh Tempo"
            }
        ));
        tbldatapinjaman1.setFocusable(false);
        tbldatapinjaman1.setGridColor(new java.awt.Color(153, 153, 153));
        tbldatapinjaman1.setRowHeight(25);
        tbldatapinjaman1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane6.setViewportView(tbldatapinjaman1);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Laporan Data Pinjaman");

        btn_tambah5.setBackground(new java.awt.Color(0, 153, 255));
        btn_tambah5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tambah5.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah5.setText("CETAK");
        btn_tambah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_pinjaman1Layout = new javax.swing.GroupLayout(data_pinjaman1);
        data_pinjaman1.setLayout(data_pinjaman1Layout);
        data_pinjaman1Layout.setHorizontalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addGroup(data_pinjaman1Layout.createSequentialGroup()
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(btn_tambah5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        data_pinjaman1Layout.setVerticalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(14, 14, 14)
                .addComponent(btn_tambah5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        main_panel.add(data_pinjaman1, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah5ActionPerformed
        // TODO add your handling code here:
        String jdbc_driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String pswd = "";
        String url = "jdbc:mysql://localhost/koperasi";
        File reportTotalPinjaman = new File(".");
        String dirr = "";
        
        try {
        Class.forName(jdbc_driver);
            Connection cnc = (Connection) DriverManager.getConnection(url, user, pswd);
            stat = cnc.createStatement();
            String sql = "SELECT * FROM pinjaman_guru";
            dirr = reportTotalPinjaman.getCanonicalPath() + "/src/report/totalPinjaman/";
            JasperDesign design =  JRXmlLoader.load(dirr + "reportTotalPinjaman.jrxml");
            JasperReport rep = JasperCompileManager.compileReport(design);
            res = stat.executeQuery(sql);
            JRResultSetDataSource resDataSource = new JRResultSetDataSource(res);
            JasperPrint jp = JasperFillManager.fillReport(rep, new HashMap(), resDataSource);
            JasperViewer.viewReport(jp, false); // false biar gak nge-block aplikasi
            JasperExportManager.exportReportToPdfFile(jp, dirr + "reportTotalPinjaman.pdf");

        } catch (ClassNotFoundException | SQLException | IOException |
                JRException ex) {
            JOptionPane.showMessageDialog(null, "\n Gagal Mencetak\n" + 
                    ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambah5ActionPerformed

    
        


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tambah5;
    private javax.swing.JPanel data_pinjaman1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTable tbldatapinjaman1;
    // End of variables declaration//GEN-END:variables

}
