/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package masterTransaksi;

/**
 *
 * @author Admin
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import masterData.*;
import java.sql.*;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
public class peminjaman1 extends javax.swing.JPanel {

     public Statement stat;
    public ResultSet res;
    Connection cn = config.koneksi.BukaKoneksi();
    NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in", "ID"));
    String sql;
    
    public peminjaman1() {
        initComponents();
        bersih();
        TampilData();
        
         JTableHeader header = tbldatapinjaman1.getTableHeader();
    header.setDefaultRenderer(new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

        JLabel label = (JLabel) super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);
        
        label.setBackground(new Color(32, 136, 203)); // biru
        label.setForeground(Color.WHITE); // teks putih
        label.setFont(new Font("Segoe UI", Font.BOLD, 15));
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setOpaque(true); // WAJIB supaya background tampil

        return label;
    }
});
        
    }
    
   private void hitungTotalPinjamanOtomatis() {
    try {
        double jumlah = Double.parseDouble(tx_jumlahPinjaman.getText().replace(",", "."));
        double persen = Double.parseDouble(tx_persenBunga.getText().replace(",", "."));

        double bunga = (jumlah * persen) / 100.0;
        double total = jumlah + bunga;

        // Format hasil ke string dengan 2 angka di belakang koma, menggunakan titik sebagai desimal
        tx_totalBunga.setText(String.format(Locale.US, "%.2f", bunga));
        tx_totalPinjaman.setText(String.format(Locale.US, "%.2f", total));

    } catch (NumberFormatException e) {
        tx_totalBunga.setText("");
        tx_totalPinjaman.setText("");
    }
}



    
    public void TampilData() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Id", "Nama Guru", "Jenis Pinjaman",
                             "Jumlah Pinjaman", "Tanggal Pinjam", "Jatuh Tempo"}, 0);

            stat = cn.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM pinjaman_guru");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("nama_guru"),
                    rs.getString("jenis_pinjaman"),
                    rs.getInt("jumlah_pinjaman"),
                    rs.getDate("tanggal_pinjam"),
                    rs.getDate("tanggal_jatuh_tempo")
                });
            }
            tbldatapinjaman1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menampilkan data: " + e.getMessage());
        }
    }    

    private void kodeBarang() {
        if (cb_idGuru.getSelectedItem() == "Pilih Id Guru") {
            return;
        }

        String kode = cb_idGuru.getSelectedItem().toString();

        try {
            sql = "SELECT nama_guru FROM data_guru WHERE Id = ?";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, kode);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                tx_namaGuru.setText(rs.getString("nama_guru"));

                // Set fokus dan tidak bisa diedit
            } else {
                // Jika data tidak ditemukan
                tx_namaGuru.setText("");
                JOptionPane.showMessageDialog(this, "Data guru tidak ditemukan.");
            }

            // Tutup statement dan result
            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data guru: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main_panel = new javax.swing.JPanel();
        data_pinjaman1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbldatapinjaman1 = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_idGuru = new javax.swing.JComboBox<>();
        tx_namaGuru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_jumlahPinjaman = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_persenBunga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDate_tglPinjaman = new com.toedter.calendar.JDateChooser();
        jDate_jatuhTempo = new com.toedter.calendar.JDateChooser();
        tx_totalBunga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tx_totalPinjaman = new javax.swing.JTextField();
        cb_jenisPinjaman = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        data_pinjaman1.setBackground(new java.awt.Color(255, 255, 255));

        tbldatapinjaman1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbldatapinjaman1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Guru", "Jenis Pinjaman", "Jumlah Pinjaman", "Tanggal Pinjaman", "Jatuh Tempo"
            }
        ));
        tbldatapinjaman1.setFocusable(false);
        tbldatapinjaman1.setGridColor(new java.awt.Color(153, 153, 153));
        tbldatapinjaman1.setRowHeight(25);
        tbldatapinjaman1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane6.setViewportView(tbldatapinjaman1);

        btn_simpan.setBackground(new java.awt.Color(0, 153, 255));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.setPreferredSize(new java.awt.Dimension(81, 25));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Id");

        cb_idGuru.setBackground(new java.awt.Color(0, 153, 255));
        cb_idGuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Id Guru", "G01", "G02", "G03", "G04", "G05", "G06", "G07", "G08", "G09", "G010", "G11", "G12", "G13", "G14", "G15", "G16", "G17", "G18", "G19", "G20", "G21", "G22", "G23", "G24", "G25", "G26", "G27", "G28", "G29", "G30", "G31", "G32", "G33", " " }));
        cb_idGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_idGuruActionPerformed(evt);
            }
        });
        cb_idGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cb_idGuruKeyReleased(evt);
            }
        });

        jLabel4.setText("Nama Guru");

        jLabel5.setText("Jenis Pinjaman");

        jLabel6.setText("Jumlah Pinjaman");

        tx_persenBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_persenBungaActionPerformed(evt);
            }
        });

        jLabel8.setText("Bunga %");

        jLabel9.setText("JatuhTempo");

        jLabel10.setText("Tanggal Pinjaman");

        jDate_tglPinjaman.setBackground(new java.awt.Color(255, 255, 255));

        jDate_jatuhTempo.setBackground(new java.awt.Color(255, 255, 255));

        tx_totalBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_totalBungaActionPerformed(evt);
            }
        });

        jLabel12.setText("Total Pinjaman");

        tx_totalPinjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_totalPinjamanKeyReleased(evt);
            }
        });

        cb_jenisPinjaman.setBackground(new java.awt.Color(0, 153, 255));
        cb_jenisPinjaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pinjaman", "Konsumtif", "Produktif", " " }));

        javax.swing.GroupLayout data_pinjaman1Layout = new javax.swing.GroupLayout(data_pinjaman1);
        data_pinjaman1.setLayout(data_pinjaman1Layout);
        data_pinjaman1Layout.setHorizontalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_jumlahPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tx_namaGuru)
                        .addComponent(cb_idGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_jenisPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDate_tglPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDate_jatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(data_pinjaman1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(62, 62, 62)
                            .addComponent(tx_persenBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tx_totalBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pinjaman1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tx_totalPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );
        data_pinjaman1Layout.setVerticalGroup(
            data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pinjaman1Layout.createSequentialGroup()
                .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_pinjaman1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_idGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_jumlahPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_jenisPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(data_pinjaman1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jDate_tglPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDate_jatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_persenBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tx_totalBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(data_pinjaman1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_totalPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        main_panel.add(data_pinjaman1, "card2");

        jPanel1.add(main_panel, "card2");

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tx_persenBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_persenBungaActionPerformed
        hitungTotalPinjamanOtomatis();
    }//GEN-LAST:event_tx_persenBungaActionPerformed

    private void cb_idGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_idGuruActionPerformed
        kodeBarang();
        String selected = cb_idGuru.getSelectedItem().toString();
        if (selected.equals("Silahkan pilih data guru")) {
        tx_namaGuru.setText("");
     return;
}

    }//GEN-LAST:event_cb_idGuruActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
      String id = cb_idGuru.getSelectedItem().toString();
    String namaGuru = tx_namaGuru.getText();
    String jenisPinjaman = cb_jenisPinjaman.getSelectedItem().toString();

    int jumlahPinjaman = 0;

    try {
        // Cek input tanggal kosong
        if (jDate_tglPinjaman.getDate() == null || jDate_jatuhTempo.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal pinjam dan jatuh tempo wajib diisi!");
            return;
        }

        // Cek input jumlah
       if (!tx_totalPinjaman.getText().isEmpty()) {
    // Total pinjaman diinput manual, pastikan format angka valid (hanya titik jika ada desimal)
    double total = Double.parseDouble(tx_totalPinjaman.getText());
    jumlahPinjaman = (int) Math.round(total); // bulatkan ke int
} else {
    // Hitung dari jumlah pinjaman + bunga
    double jumlah = Double.parseDouble(tx_jumlahPinjaman.getText());
    double persen = Double.parseDouble(tx_persenBunga.getText());

    double bunga = (jumlah * persen) / 100;
    double total = jumlah + bunga;

    jumlahPinjaman = (int) Math.round(total); // bulatkan ke int
}


        java.sql.Date tglPinjam = new java.sql.Date(jDate_tglPinjaman.getDate().getTime());
        java.sql.Date tglJatuhTempo = new java.sql.Date(jDate_jatuhTempo.getDate().getTime());

        if (btn_simpan.getText().equalsIgnoreCase("SIMPAN")) {
            sql = "INSERT INTO pinjaman_guru (Id, nama_guru, jenis_pinjaman, "
                + "jumlah_pinjaman, tanggal_pinjam, tanggal_jatuh_tempo) "
                + "VALUES (?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, namaGuru);
            pst.setString(3, jenisPinjaman);
            pst.setInt(4, jumlahPinjaman);
            pst.setDate(5, tglPinjam);
            pst.setDate(6, tglJatuhTempo);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        }

        bersih();
        TampilData();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input angka tidak valid (gunakan titik untuk desimal): " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tx_totalPinjamanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_totalPinjamanKeyReleased
        hitungTotalPinjamanOtomatis();
    }//GEN-LAST:event_tx_totalPinjamanKeyReleased

    private void tx_totalBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_totalBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_totalBungaActionPerformed

    private void cb_idGuruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_idGuruKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_idGuruKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_idGuru;
    private javax.swing.JComboBox<String> cb_jenisPinjaman;
    private javax.swing.JPanel data_pinjaman1;
    private com.toedter.calendar.JDateChooser jDate_jatuhTempo;
    private com.toedter.calendar.JDateChooser jDate_tglPinjaman;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTable tbldatapinjaman1;
    private javax.swing.JTextField tx_jumlahPinjaman;
    private javax.swing.JTextField tx_namaGuru;
    private javax.swing.JTextField tx_persenBunga;
    private javax.swing.JTextField tx_totalBunga;
    private javax.swing.JTextField tx_totalPinjaman;
    // End of variables declaration//GEN-END:variables
private void bersih() {
    cb_idGuru.setSelectedIndex(0); // Atur kembali ke pilihan pertama
    tx_namaGuru.setText("");
    tx_jumlahPinjaman.setText("");
    cb_jenisPinjaman.setSelectedIndex(0); // Atur kembali ke pilihan pertama
    jDate_tglPinjaman.setDate(null); // Kosongkan tanggal
    tx_persenBunga.setText("");
    tx_totalBunga.setText("");
    tx_totalPinjaman.setText("");

}


}


